### PR TITLE
use XDG_CACHE_HOME for cache

### PR DESCRIPTION
**Pull request by nl6720**

### CODE REVIEW

**Comment by falconindy** [comment]
Seems weird to me to move the cache and not just the entire ASPROOT. The cache is tiny (~160k), and will only grow/shrink based on the repositories changing size.

**Comment by nl6720** [comment]
Reading #7 left me with the impression that you would not support moving ASPROOT to XDG_DATA_HOME.

**Comment by falconindy** [comment]
And that's still mostly true, but you're free to relocate ASPROOT wherever you like in your own install.

**Comment by nl6720** [comment]
Personally I don't want to move ASPROOT, just the ASPCACHE, but I don't want to set the ASPCACHE variable.
And keeping cache in XDG_CACHE_HOME allows to easily skip all caches when doing backups.

**Comment by falconindy** [comment]
...and this is the nature of preferences.

**Pull request closed without merging**
